package convertor;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author nattogaboh
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        cmb1 = new javax.swing.JComboBox();
        cmb2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        txt2.setEditable(false);
        txt2.setBackground(new java.awt.Color(209, 202, 202));
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        cmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "onzas", "libras", "kg", "gramos" }));
        cmb1.setName("gramos\nkg\nonzas\nlibras\n"); // NOI18N

        cmb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "gramos", "Kg", "onzas", "libras" }));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 16)); // NOI18N
        jLabel1.setText("Convertor de Medidas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/////////////DECIMALES
    DecimalFormat decimales = new DecimalFormat("0.00");

        // Declarando Variables: 
        String nn=txt1.getText();
        if (nn.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un Dígito","LAPSUS", JOptionPane.DEFAULT_OPTION);
        }else{
        double n1;
        n1=Double.parseDouble(txt1.getText());
        int op=cmb1.getSelectedIndex();
     
        //Con Gramos
        if (op==0) {
            double oz=ozAgramo(n1);
            txt2.setText(decimales.format(oz));
        }
        if (op==1) {
            double lb=lbAgramo(n1);
            txt2.setText(decimales.format(lb));
        }
        if (op==2) {
            double kg=kgAgramo(n1);
            txt2.setText(decimales.format(kg));
        }
     
        //Segundo COMBOBOX
        int op2=cmb2.getSelectedIndex();
            
            //Con kg
            if (op2==1 && op==0) {
                double oz=ozAkg(n1);
                txt2.setText(decimales.format(oz));
            }
            if (op2==1 && op==1) {
                double lb=lbAkg(n1);
                txt2.setText(decimales.format(lb));
            }
            if (op2==1 && op==3) {
                double gr=grAkg(n1);
                txt2.setText(decimales.format(gr));
            }
        
            //Con Onzas
            if (op==1 && op2==2) {
                double lb=lbAoz(n1);
                txt2.setText(decimales.format(lb));
            }
            if (op==2 && op2==2) {
                double kg=kgAoz(n1);
                txt2.setText(decimales.format(kg));
            }
            if (op==3 && op2==2) {
                double gr=grAoz(n1);
                txt2.setText(decimales.format(gr));
            }
            
            //Con libras
            if (op==0 && op2==3) {
                double oz=ozAlb(n1);
                txt2.setText(decimales.format(oz));
            }
            if (op==2 && op2==3) {
                double kg=kgAlb(n1);
                txt2.setText(decimales.format(kg));
            }
            if(op==3 && op2==3){
                double gr=grAlb(n1);
                txt2.setText(decimales.format(gr));
            }
        }
        
//Iniciar en Caja de Texto1
        txt1.requestFocus();        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    ////////////////Operaciones en Gramos
    public static double kgAgramo(double n1){
        double gramo;
        gramo=n1*1000;
        return gramo;    
    }
    
    public static double ozAgramo(double n1){
        double gramo;
        gramo=n1/0.035274;
        return gramo;
    }
    
    public static double lbAgramo(double n1){
        double gramo;
        gramo=n1/0.0022046;
        return gramo;
    }
    //////////////Operaciones en Kg
    public static double ozAkg(double n1){
        double kg;
        kg=n1/35.274;
        return kg;
    }
    public static double lbAkg(double n1){
        double kg;
        kg=n1/2.2046;
        return kg;
    }
    public static double grAkg(double n1){
        double kg;
        kg=n1/1000;
        return kg;
    }
   //////////////Operaciones en Onzas
    public static double lbAoz(double n1){
        double oz;
        oz=n1*16;
        return oz;
    }
    public static double kgAoz(double n1){
        double oz;
        oz=n1*35.274;
        return oz;
    }
    public static double grAoz(double n1){
        double oz;
        oz=n1*0.035274;
        return oz;
    }
    /////////////Operaciones en libras
    public static double ozAlb(double n1){
        double lb;
        lb=n1/0.0625;
        return lb;
    }
    public static double kgAlb(double n1){
        double lb;
        lb=n1*2.2046;
        return lb;
    }
    public static double grAlb(double n1){
        double lb;
        lb=n1*0.0022046;
        return lb;
    }
    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        // TODO add your handling code here:
        
        char x;
        x=evt.getKeyChar();
        if (Character.isLetter(x) || x==',') {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txt1KeyTyped

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        // TODO add your handling code here:
        char x=evt.getKeyChar();
        if (x<'0' || x>'9') {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb1;
    private javax.swing.JComboBox cmb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
